### PR TITLE
folder student with front-end php and some style

### PR DESCRIPTION
**Pull request by luisanogueira**
Mario, I created an index for the student page and included header and footer files into it. I already used some style Scss and added bootstrap. Please include my folder student with the files in your Git.

### CODE REVIEW

**Comment by Mario-Weiss** [comment]
Hi Luisa, can you please change somethings:

all files related to the web page should go to the app folder.
all css files need to go to app/css
all files for the view should go to the app/view folder.

in the app/index.php you can inlude your header & footer
we still need to decide if we are going to put all files like student.php to the view folder or if we will keep them in the root.

But it is very important to keep a clean file structure and have the Models / Controllers / Views separated

**Comment by Mario-Weiss** [comment]
for testing and other purposes you can also use the "other stuff" folder

**Comment by luisanogueira** [comment]
Tomorrow I change the location of the files then.
Yeah, I looked at how they were structured using symfony and it is like this indeed.

**Comment by luisanogueira** [comment]
Please merge.

**Review by Mario-Weiss — APPROVED** [review]

**Pull request merged**
